### ISSUE TITLE
Publish schema on http://schemastore.org/json/

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#50]
**What is the problem you're trying to solve**
schema can be used to offer IDE autocompletion and validation.

**Describe the solution you'd like**
schemastore.org do define an API for IDE to download schema
(https://www.jetbrains.com/help/idea/json.html)
we just have to publish compose schema to offer users autocompletion 

**Additional context**
Initialy proposed by https://github.com/docker/compose/issues/2089#issuecomment-408919895

**Comment by ZiQiLN** [comment]
@ndeloof Do somebody done that, or I should do it on my own - because it would be usable for me and some time passed away since there was issues on it, I haven't seen that on schemastore.

**Comment by ZiQiLN** [comment]
Ahhh... Fuck, I'll take part in this.

**Comment by ZiQiLN** [comment]
Actually opened a PR to SchemaStore with docker-spec. Thanks for your awesome configuration, let's make it usable.

https://github.com/SchemaStore/schemastore/pull/1153

**Comment by ZiQiLN** [comment]
Merge completed, Enjoyable! 🎉

@ndeloof Issue can be closed :)

**Comment by EricHripko** [comment]
Thanks for your help with this @ZiQiLN 👍 I've asked the approver of your PR to confirm if we can simply link out to this repo. This would simplify maintenance, as schema would be referenced from one place (thereby avoiding duplication and the need to keep these in sync).

**Comment by ZiQiLN** [comment]
Actually I made a little mistake with adding a schema in JSON, because in catalog I've added raw from your GitHub repo.

**Comment by EricHripko** [comment]
Ah, I see - sorry, didn't check the large diff. Would you like to submit a follow-up PR to finish that up or should we do it?

Also, we should add `compose.y(a)ml` to the `fileMatch` - as per the [spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file).

**Comment by ZiQiLN** [comment]
Oh, sorry. I was not aware about compose.yml , I can follow up my PR but not today, at general it isn't a much problem for me. And additional question, does your files should be stored in SchemaStore in fixed version or should I link a repository raw?

Jakub "Jay" OlanNode.js Software Enginner
jakub.jay.olan@gmail.com (https://link.getmailspring.com/link/22452B62-7611-46DB-8ED8-6A087619B196@getmailspring.com/0?redirect=mailto%3Ajakub.jay.olan%40gmail.com&recipient=cmVwbHkrQUo2NzYyNlNKRzVMUk5YQ0VET1JETzU1RTJGNUpFVkJOSEhDREhBU05FQHJlcGx5LmdpdGh1Yi5jb20%3D)
+48 664 046 173 (tel:+48%20664%20046%20173)
Szydłowiec, Poland (https://link.getmailspring.com/link/22452B62-7611-46DB-8ED8-6A087619B196@getmailspring.com/1?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3DSzyd%25C5%2582owiec%252C%2520Poland&recipient=cmVwbHkrQUo2NzYyNlNKRzVMUk5YQ0VET1JETzU1RTJGNUpFVkJOSEhDREhBU05FQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by EricHripko** [comment]
Resolved as per PRs above - thank you @ZiQiLN for helping out with this functionality 🙌

**Comment by AlexRMU** [comment]
The file is currently unavailable for some reason.
You can use this link: https://cdn.jsdelivr.net/gh/SchemaStore/schemastore@55438674c8ee173f6a0b23501c5c11a5fe1ed972/src/schemas/json/docker-compose.json
By the way, you forgot to add the `$schema` field.
